### ISSUE TITLE
afButter::ButterRequest.body OutStream options

### ISSUE THREAD

**Issue by Donklord** [SlimerDude/afButter#1]
Unless im missing something, is it possible to expose the OutStream for ButterRequest?  In using the SkyFoundry haystack.pod file, i need to pass in the OutStream into JsonWriter to get the request submitted properly.

**Comment by SlimerDude** [comment]
Try:

    out := butterRequest.body.buf.out

And don't forget you can always create your own `Buf` to pass to `JsonWriter`, then read it back as a Str to `echo` or set as the request body.

Programming in new APIs is very much like *connect-the-dots*!
